/**
 * Récuperer les données de l'api
 */
fetch("http://localhost:3000/api/products")
  .then((resp) => resp.json())
  .then(function (produits) {
    for (let produit of produits) {
      // pour chaque produit dans produits je crée une balise dans le DOM
      let a = document.createElement("a"); // je crée une balise "a"
      let article = document.createElement("article"); //...
      let img = document.createElement("img"); //...
      let titre = document.createElement("h3"); //...
      let p = document.createElement("p"); //...
      let section = document.getElementById("items"); //...

      // pour chaque balises créé j'assigne leurs place dans le DOM en fonction de la balise parent
      section.appendChild(a); // La variable a sera l'enfant de la variable section
      a.appendChild(article); //...
      article.appendChild(img); //...
      article.appendChild(titre); //...
      article.appendChild(p); //...

      // on inserer les valeurs des produits dans les variables
      a.href = "./product.html?id=" + produit._id; // insertion de l'id dans la balise a
      img.src = produit.imageUrl; //...
      titre.textContent = produit.name; //...
      p.textContent = produit.description; //...
    }
  });
